spring:
  profiles: development

startRoute: timer:hello?period=10000
fromRoute: file:data/input?delete=true&readLock=none
toRoute1: file:data/output
toRoute2: jdbc:dataSource

message: DEVELOPMENT environment
