spring:
  profiles:
    active: development
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/localDB

startRoute: timer:hello?period=10000
fromRoute: file:data/input?delete=true&readLock=none
toRoute1: file:data/output
toRoute2: jdbc:dataSource
toRoute3: file:data/output?fileName=success.txt

camel:
  springboot:
    shutdownTimeout: 2
