CREATE TABLE ITEMS (
    ITEM_I SERIAL,
    SKU TEXT NOT NULL,
    ITEM_DESCRIPTION TEXT NOT NULL,
    PRICE NUMERIC (5,2) NOT NULL,
    CREATE_TS TIMESTAMPTZ NULL DEFAULT current_timestamp
);

select * from items;
